import type { Service, PortfolioItem, Article, ClientLogo, AdminUser, MediaItem, IGDraft } from "./storage";

const LOGO = "https://gallery.bytecorner.site/uploads/2026-05-09/80635211a9ef6f4cde714c92fa9a3a2c_1778356173.png";

// Use Unsplash for nice mock visuals
const u = (q: string, w = 1200) =>
  `https://images.unsplash.com/${q}?auto=format&fit=crop&w=${w}&q=80`;

export const seedServices: Service[] = [
  {
    id: "s1", slug: "web-development", category: "Development",
    title: { id: "Web Development", en: "Web Development" },
    excerpt: {
      id: "Pengembangan website modern, cepat, aman, dan scalable.",
      en: "Modern, fast, secure and scalable websites built to grow your business.",
    },
    description: {
      id: "Kami membangun website performant menggunakan teknologi terkini, mendukung pertumbuhan bisnis dengan arsitektur scalable, SEO-friendly dan mudah dikelola.",
      en: "We build performant websites with the latest tech stack, scalable architecture, SEO-friendly markup and easy content management.",
    },
    icon: "Code2", image: u("photo-1551434678-e076c223a692"),
    features: ["High Performance", "Scalable & Secure", "SEO Friendly", "Easy to Manage"],
    faq: [
      { q: "How long does a website take?", a: "Typical builds run 4–10 weeks depending on scope." },
      { q: "Do you provide ongoing support?", a: "Yes, we offer monthly maintenance & growth packages." },
    ],
    status: "published", featured: true,
  },
  {
    id: "s2", slug: "ui-ux-design", category: "Design",
    title: { id: "UI/UX Design", en: "UI/UX Design" },
    excerpt: { id: "Desain antarmuka yang intuitif dan berorientasi pengguna.", en: "Intuitive, user-centred interfaces that convert." },
    description: { id: "Riset, wireframing, design system dan prototyping untuk pengalaman digital yang berkesan.", en: "Research, wireframing, design systems and prototyping for memorable digital experiences." },
    icon: "Palette", image: u("photo-1558655146-9f40138edfeb"),
    features: ["User Research", "Wireframing & Prototyping", "Design System", "Usability Testing"],
    faq: [{ q: "Do you handle handoff?", a: "Yes, we deliver Figma files and a developer handoff doc." }],
    status: "published",
  },
  {
    id: "s3", slug: "digital-marketing", category: "Marketing",
    title: { id: "Digital Marketing", en: "Digital Marketing" },
    excerpt: { id: "Strategi pemasaran digital untuk meningkatkan brand & penjualan.", en: "Digital marketing strategies that grow brand and sales." },
    description: { id: "SEO, paid ads, content marketing dan social yang terukur.", en: "Measurable SEO, paid ads, content and social campaigns." },
    icon: "Megaphone", image: u("photo-1460925895917-afdab827c52f"),
    features: ["SEO Optimisation", "Paid Acquisition", "Content Strategy", "Performance Tracking"],
    faq: [], status: "published",
  },
  {
    id: "s4", slug: "mobile-development", category: "Development",
    title: { id: "Mobile Development", en: "Mobile Development" },
    excerpt: { id: "Aplikasi mobile berkualitas tinggi untuk iOS & Android.", en: "High-quality mobile apps for iOS & Android." },
    description: { id: "Native dan cross-platform mobile development.", en: "Native and cross-platform mobile development." },
    icon: "Smartphone", image: u("photo-1512941937669-90a1b58e7e9c"),
    features: ["iOS & Android", "Cross-platform", "Push & Realtime", "App Store Launch"],
    faq: [], status: "published",
  },
  {
    id: "s5", slug: "company-profile-website", category: "Website",
    title: { id: "Company Profile Website", en: "Company Profile Website" },
    excerpt: { id: "Website profesional untuk membangun kredibilitas bisnis.", en: "Professional websites to build business credibility." },
    description: { id: "Website company profile premium yang memperkuat brand Anda.", en: "Premium company profile sites that strengthen your brand." },
    icon: "Building2", image: u("photo-1497366216548-37526070297c"),
    features: ["Custom Design", "CMS Built-in", "Mobile Friendly", "SEO Ready"],
    faq: [], status: "published",
  },
  {
    id: "s6", slug: "landing-page", category: "Website",
    title: { id: "Landing Page", en: "Landing Page" },
    excerpt: { id: "Halaman khusus yang dioptimalkan untuk konversi maksimal.", en: "Dedicated pages optimised for maximum conversion." },
    description: { id: "Landing page berperforma tinggi untuk kampanye Anda.", en: "High-performing landing pages for your campaigns." },
    icon: "Rocket", image: u("photo-1432888622747-4eb9a8efeb07"),
    features: ["A/B Tested", "Fast Loading", "Lead Capture", "Analytics"],
    faq: [], status: "published",
  },
  {
    id: "s7", slug: "strategy-digital", category: "Strategy",
    title: { id: "Strategy Digital", en: "Digital Strategy" },
    excerpt: { id: "Riset & strategi digital yang tepat sasaran dan terukur.", en: "Accurate, measurable digital strategy & research." },
    description: { id: "Konsultasi strategi end-to-end.", en: "End-to-end strategy consulting." },
    icon: "Target", image: u("photo-1552664730-d307ca884978"),
    features: ["Market Research", "Competitor Analysis", "Roadmap", "KPI Framework"],
    faq: [], status: "published",
  },
];

export const seedPortfolio: PortfolioItem[] = [
  {
    id: "p1", slug: "paragon-technology", client: "Paragon Technology", category: "Website",
    title: { id: "Paragon Technology — Corporate Website Redesign", en: "Paragon Technology — Corporate Website Redesign" },
    description: { id: "Redesain website korporat dengan pendekatan modern.", en: "Corporate redesign with modern, performant approach." },
    overview: { id: "Redesain menyeluruh untuk meningkatkan trafik, lead, dan persepsi brand.", en: "A full redesign aimed at growing traffic, leads and brand perception." },
    challenge: { id: "Website lama lambat dan tidak mobile-friendly.", en: "The old site was slow and not mobile-friendly." },
    solution: { id: "Arsitektur baru, design system fresh, performance-first.", en: "New architecture, fresh design system, performance-first build." },
    techStack: ["Next.js", "Tailwind", "Sanity"],
    date: "2024-04-12", featured: true,
    cover: u("photo-1497366216548-37526070297c"),
    gallery: [u("photo-1497366216548-37526070297c"), u("photo-1499951360447-b19be8fe80f5"), u("photo-1517245386807-bb43f82c33c4")],
    status: "published",
    metrics: [{ label: "Traffic +", value: "125%" }, { label: "Leads +", value: "68%" }, { label: "Performance", value: "98/100" }],
  },
  {
    id: "p2", slug: "koinworks-dashboard", client: "KoinWorks", category: "Web App",
    title: { id: "KoinWorks Dashboard", en: "KoinWorks Dashboard" },
    description: { id: "Dashboard finansial untuk monitoring kinerja real-time.", en: "Financial dashboard for real-time performance monitoring." },
    overview: { id: "", en: "Realtime fintech dashboard." },
    challenge: { id: "", en: "Complex data, lots of users." },
    solution: { id: "", en: "Modular charts, role-based views." },
    techStack: ["React", "Recharts", "Node.js"],
    date: "2024-03-20",
    cover: u("photo-1551288049-bebda4e38f71"),
    gallery: [u("photo-1551288049-bebda4e38f71"), u("photo-1460925895917-afdab827c52f")],
    status: "published",
  },
  {
    id: "p3", slug: "ruangguru-learning", client: "Ruangguru", category: "Mobile App",
    title: { id: "Ruangguru Learning App", en: "Ruangguru Learning App" },
    description: { id: "Aplikasi mobile untuk platform belajar online.", en: "Mobile app for online learning platform." },
    overview: { id: "", en: "Engaging mobile learning experience." },
    challenge: { id: "", en: "Diverse student personas." },
    solution: { id: "", en: "Personalised recommendations." },
    techStack: ["React Native", "Firebase"],
    date: "2024-03-05",
    cover: u("photo-1512941937669-90a1b58e7e9c"),
    gallery: [u("photo-1512941937669-90a1b58e7e9c")],
    status: "published",
  },
  {
    id: "p4", slug: "danamon-prioritas", client: "Danamon", category: "Branding",
    title: { id: "Danamon Prioritas Brand Identity", en: "Danamon Prioritas Brand Identity" },
    description: { id: "Perancangan ulang identitas visual untuk layanan perbankan prioritas.", en: "Visual identity redesign for priority banking service." },
    overview: { id: "", en: "Premium banking brand redesign." },
    challenge: { id: "", en: "Modernise without losing trust." },
    solution: { id: "", en: "Refined typography & palette." },
    techStack: ["Figma", "Illustrator"],
    date: "2024-02-18",
    cover: u("photo-1559526324-4b87b5e36e44"),
    gallery: [u("photo-1559526324-4b87b5e36e44")],
    status: "published",
  },
  {
    id: "p5", slug: "traveloka-redesign", client: "Traveloka", category: "Website",
    title: { id: "Traveloka Redesign", en: "Traveloka Redesign" },
    description: { id: "Redesign website travel dengan UI/UX modern.", en: "Modern travel website UI/UX redesign." },
    overview: { id: "", en: "Travel discovery rebuilt." },
    challenge: { id: "", en: "High-density product data." },
    solution: { id: "", en: "Smart filters & previews." },
    techStack: ["Next.js", "TypeScript"],
    date: "2024-01-30",
    cover: u("photo-1488646953014-85cb44e25828"),
    gallery: [u("photo-1488646953014-85cb44e25828")],
    status: "published",
  },
  {
    id: "p6", slug: "glints-recruitment", client: "Glints", category: "Web App",
    title: { id: "Glints Recruitment Platform", en: "Glints Recruitment Platform" },
    description: { id: "Platform rekrutmen dengan fitur pencarian yang efisien.", en: "Recruitment platform with efficient search." },
    overview: { id: "", en: "Recruiter & candidate dashboards." },
    challenge: { id: "", en: "Matching at scale." },
    solution: { id: "", en: "Smart filtering & AI suggestions." },
    techStack: ["React", "GraphQL"],
    date: "2024-01-15",
    cover: u("photo-1542744173-8e7e53415bb0"),
    gallery: [u("photo-1542744173-8e7e53415bb0")],
    status: "published",
  },
  {
    id: "p7", slug: "halodoc-redesign", client: "Halodoc", category: "Mobile App",
    title: { id: "Halodoc Mobile App Redesign", en: "Halodoc Mobile App Redesign" },
    description: { id: "Pembaruan UI/UX aplikasi kesehatan.", en: "Health app UI/UX refresh." },
    overview: { id: "", en: "Healthcare reimagined." },
    challenge: { id: "", en: "Calm yet medical." },
    solution: { id: "", en: "Soft palette, clear hierarchy." },
    techStack: ["Flutter"],
    date: "2024-01-04",
    cover: u("photo-1576091160550-2173dba999ef"),
    gallery: [u("photo-1576091160550-2173dba999ef")],
    status: "published",
  },
  {
    id: "p8", slug: "fore-coffee-brand", client: "Fore Coffee", category: "Branding",
    title: { id: "Fore Coffee Brand Identity", en: "Fore Coffee Brand Identity" },
    description: { id: "Identitas visual brand kopi yang modern dan minimalis.", en: "Modern, minimal coffee brand identity." },
    overview: { id: "", en: "Crafted identity from logo to packaging." },
    challenge: { id: "", en: "Stand out in a crowded market." },
    solution: { id: "", en: "Earthy tones with bold typography." },
    techStack: ["Illustrator", "Photoshop"],
    date: "2023-12-12",
    cover: u("photo-1495474472287-4d71bcdd2085"),
    gallery: [u("photo-1495474472287-4d71bcdd2085")],
    status: "published",
  },
];

export const seedArticles: Article[] = [
  {
    id: "a1", slug: "5-strategi-digital-marketing-2024",
    title: { id: "5 Strategi Digital Marketing untuk Meningkatkan Brand Awareness 2024", en: "5 Digital Marketing Strategies to Boost Brand Awareness in 2024" },
    excerpt: { id: "Strategi digital marketing yang tepat membantu bisnis menjangkau audiens lebih luas.", en: "The right digital marketing strategy helps business reach wider audiences." },
    content: {
      id: `<p>Brand awareness adalah fondasi penting...</p><h2>1. Konten yang Konsisten</h2><p>Konsistensi membangun kepercayaan...</p><ul><li>Tetapkan jadwal posting</li><li>Pertahankan tone of voice</li></ul>`,
      en: `<p>Brand awareness is the foundation...</p><h2>1. Consistent Content</h2><p>Consistency builds trust...</p><ul><li>Set a posting schedule</li><li>Maintain tone of voice</li></ul>`,
    },
    category: "Digital Marketing", author: "Ahmad Fadly", date: "2024-05-15",
    cover: u("photo-1432888622747-4eb9a8efeb07"),
    tags: ["marketing", "branding"], featured: true, readingTime: 5, status: "published",
  },
  {
    id: "a2", slug: "ui-ux-meningkatkan-konversi",
    title: { id: "Prinsip UI/UX Design yang Meningkatkan Konversi Website", en: "UI/UX Design Principles That Boost Website Conversion" },
    excerpt: { id: "UI/UX yang baik bukan hanya soal estetika.", en: "Great UI/UX isn't just about aesthetics." },
    content: { id: `<p>Konversi dimulai dari pengalaman.</p>`, en: `<p>Conversion starts with experience.</p>` },
    category: "UI/UX", author: "Dewi Lestari", date: "2024-05-10",
    cover: u("photo-1559028012-481c04fa702d"),
    tags: ["design"], readingTime: 4, status: "published",
  },
  {
    id: "a3", slug: "tren-web-development-2024",
    title: { id: "Tren Teknologi Web Development 2024 yang Perlu Diketahui", en: "2024 Web Development Trends You Should Know" },
    excerpt: { id: "Jelajahi tren teknologi web terbaru.", en: "Explore the latest web technology trends." },
    content: { id: `<p>Tahun 2024 membawa banyak inovasi.</p>`, en: `<p>2024 brings many innovations.</p>` },
    category: "Industry Trend", author: "Ahmad Fadly", date: "2024-05-10",
    cover: u("photo-1518770660439-4636190af475"),
    tags: ["tech"], readingTime: 6, status: "published",
  },
  {
    id: "a4", slug: "7-elemen-website-profesional",
    title: { id: "7 Elemen Penting Website Profesional untuk Bisnis", en: "7 Essential Elements of a Professional Business Website" },
    excerpt: { id: "Apa yang membuat website terlihat profesional?", en: "What makes a website look professional?" },
    content: { id: `<p>Detail penting.</p>`, en: `<p>Details matter.</p>` },
    category: "Website Tips", author: "Dewi Lestari", date: "2024-05-08",
    cover: u("photo-1467232004584-a241de8bcf5d"),
    tags: ["website"], readingTime: 6, status: "published",
  },
  {
    id: "a5", slug: "membangun-brand-identity",
    title: { id: "Cara Membangun Brand Identity yang Kuat di Era Digital", en: "Building a Strong Brand Identity in the Digital Era" },
    excerpt: { id: "Brand identity adalah jiwa perusahaan.", en: "Brand identity is the soul of a company." },
    content: { id: `<p>Mulai dari nilai inti.</p>`, en: `<p>Start with core values.</p>` },
    category: "Digital Branding", author: "Ahmad Fadly", date: "2024-05-07",
    cover: u("photo-1611224923853-80b023f02d71"),
    tags: ["branding"], readingTime: 5, status: "published",
  },
  {
    id: "a6", slug: "best-practice-web-modern",
    title: { id: "Best Practice dalam Pengembangan Web Modern", en: "Best Practices in Modern Web Development" },
    excerpt: { id: "Standar kualitas yang membedakan.", en: "The quality standards that set you apart." },
    content: { id: `<p>Performance, accessibility, security.</p>`, en: `<p>Performance, accessibility, security.</p>` },
    category: "Coding Tips", author: "Ahmad Fadly", date: "2024-05-05",
    cover: u("photo-1461749280684-dccba630e2f6"),
    tags: ["coding"], readingTime: 7, status: "published",
  },
  {
    id: "a7", slug: "kecepatan-website-seo",
    title: { id: "Mengoptimalkan Kecepatan Website untuk SEO", en: "Optimising Website Speed for SEO" },
    excerpt: { id: "Setiap detik berarti.", en: "Every second counts." },
    content: { id: `<p>Speed = SEO.</p>`, en: `<p>Speed equals SEO.</p>` },
    category: "Website Tips", author: "Dewi Lestari", date: "2024-05-04",
    cover: u("photo-1460925895917-afdab827c52f"),
    tags: ["seo"], readingTime: 4, status: "published",
  },
];

export const seedLogos: ClientLogo[] = [
  { id: "l1", name: "BCA", image: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Bank_Central_Asia.svg" },
  { id: "l2", name: "Tokopedia", image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Tokopedia.svg" },
  { id: "l3", name: "Traveloka", image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Traveloka_Primary_Logo.svg" },
  { id: "l4", name: "Danamon", image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Bank_Danamon_logo.svg" },
  { id: "l5", name: "KoinWorks", image: "https://1000logos.net/wp-content/uploads/2023/01/KoinWorks-Logo.png" },
  { id: "l6", name: "Paragon", image: "https://upload.wikimedia.org/wikipedia/commons/8/87/Paragon_Technology_and_Innovation.png" },
  { id: "l7", name: "Glints", image: "https://glints.com/id/lowongan/wp-content/uploads/sites/3/2020/12/glints-logo.png" },
  { id: "l8", name: "Ruangguru", image: "https://upload.wikimedia.org/wikipedia/commons/8/85/Ruangguru_logo.png" },
];

export const seedUsers: AdminUser[] = [
  { id: "u1", name: "Ahmad Fadly", email: "admin@bytecorner.id", role: "Super Admin", password: "admin123", avatar: "https://i.pravatar.cc/120?img=12" },
  { id: "u2", name: "Dewi Lestari", email: "dewi@bytecorner.id", role: "Editor", password: "editor123", avatar: "https://i.pravatar.cc/120?img=47" },
];

export const seedMedia: MediaItem[] = [];
export const seedIG: IGDraft[] = [];

export const BRAND_LOGO = LOGO;
